### ISSUE TITLE
git pull issue

### ISSUE THREAD

**Issue by Brainarea** [spunt/bspmview#14]
Thanks a lot for this wonderful toolbox. Whenever I see a new commit i do a little git pull to update bspmview. But today it gave me the following error:
error: Cannot update the ref 'refs/remotes/origin/master': unable to append to .git/logs/refs/remotes/origin/master: Permission denied
From https://github.com/spunt/bspmview
 ! b3e8491..5597721  master     -> origin/master  (unable to update local ref)

Any idea?

**Comment by spunt** [comment]
Hi, just seeing this now. Not exactly sure why you're seeing this but after Googling it my best guess is that the permissions on your local copy were somehow changed, e.g. see:

[git-commit-problem-unable-to-append-to-git](http://stackoverflow.com/questions/6692292/git-commit-problem-unable-to-append-to-git)
[git-error-unable-to-append-to-git-logs-refs-remotes-origin-master-permission](http://stackoverflow.com/questions/2642836/git-error-unable-to-append-to-git-logs-refs-remotes-origin-master-permission)

If the above doesn't help you find a solution, try forking or cloning a fresh copy of the repository to see if that works. Best of luck!
