### ISSUE TITLE
how to use the cluster FDR correction in bspmview

### ISSUE THREAD

**Issue by Zm-Wym** [spunt/bspmview#18]
I have downloaded the latest version of bspmview, but the FDR correction is still not displayed on the interface.I would like to ask, what causes it?

**Comment by spunt** [comment]
Cluster FDR correction should appear as an option in the "Type" drop-down menu when selecting a contrast direction of either + (positive) or - (negative). This option is not visible when viewing both contrast directions (+/-), which is the default state of the viewer.
