### ISSUE TITLE
Save Table defaults to xlsx which cannot be opened in Windows

### ISSUE THREAD

**Issue by jttrs** [spunt/bspmview#4]
When saving the result table, it wants to save it as an xlsx file.  If you allow it to save with the 'xlsx' extension, Excel gives an error when opening it which states that the file extension does not match the file format.

If instead you manually chance the extension to .csv before saving the file, Excel has no problem opening it.

I'm using Windows, haven't tried on OSX.

**Comment by spunt** [comment]
Oh, this answers my previous question about `.xlsx` saving.  I haven't tested the functionality of the recent changes to writing tables on Windows just yet.  My bad.  I think the fix will simply involve writing to `xlsx` using `xlswrite` instead of `xlwrite` when running on Windows.

**Comment by jttrs** [comment]
I'm guessing you are correct.  I have to make the same switch when I code in excel output that is sensitive to the operating system.
