### ISSUE TITLE
Error when saving table over an existing table

### ISSUE THREAD

**Issue by jttrs** [spunt/bspmview#5]
I was given this error when trying to overwrite an existing file that contained Save Table results:

Error using fprintf
Invalid file identifier.  Use fopen to generate a valid file identifier.

Error in bspmview>writereport (line 3622)
    fprintf(fid,['%s' repmat(',%s',1,ncol-1) '\n'],incell{r,:});

Error in bspmview>cb_savetable (line 1428)
    if strcmpi(ext, '.csv'), writereport(allcell, fullfile(pname, fname)); return; end;

Error while evaluating uimenu Callback

**Comment by spunt** [comment]
Hmmm... I can't seem to reproduce this error. Try changing the call to `fopen` around line 3620 from 
`fid = fopen(outname,'w');`    to   `fid = fopen(outname,'w+');`

Also, have you tried saving the tables with the extension `.xlsx`? If not, I'd be curious to know if that works for you.
